### ISSUE TITLE
Issues with 2020 version of unity

### ISSUE THREAD

**Issue by Scooke96** [Elringus/UnityRawInput#11]
Just found this and started using it to detect inputs outside of unity. It works perfectly well however once I press play and test it still works fine however after pressing play again to stop the test it then seems to lag my typing on every other application apart from unity

**Comment by NALStudio** [comment]
You could try this...
It might help...?

```cs
void OnApplicationQuit()
{
    RawKeyInput.Stop();
}
```

**Comment by Elringus** [comment]
Given it's working in a previous Unity version and doesn't work in 2020, that's most likely a Unity regression. Consider sending a bug report to Unity.
