### ISSUE TITLE
rawInputBinding

### ISSUE THREAD

**Issue by vid52** [Elringus/UnityRawInput#15]
Hi.
I love this solution ! thank you.
one question more than an issue. 
is there a way to assign a RawKey from a string. the reverse of "key.ToString()"
I'd like to rebind the key mapping, so i need a way to re-assign the list of "RawKey key" on my app start-up.

**Comment by Persegan** [comment]
I think you can use (RawKey)System.Enum.Parse(typeof(RawKey), "whatever string")

**Comment by vid52** [comment]
Thanks for your reply. In the meantime, i choose a different solution. i compare the string instead of the RawKey directly

function called by (  RawKeyInput.OnKeyDown += LogKeyDown; ):
private void LogKeyDown(RawKey key)
{
if (reBindPanel.activeSelf) // active when a rebind key button is pressed , BpToRebind set to the caller button
{
 //change the text of the button by the key pressed string . I got another button to apply the key rebind that store the button text to KeyStringNext, KeyStringPrec, etc...
      BpToRebind.transform.Find("Text").GetComponent<Text>().text = key.ToString();
      reBindPanel.SetActive(false); // hide the panel " Press a key to rebind xxxx "
}
else
{
     if (key.ToString() == KeyStringNext) nextFunction();
     if (key.ToString() == KeyStringPrev) PrevFunction();
.....
