### ISSUE TITLE
One more raw mouse button request

### ISSUE THREAD

**Issue by jeffhgit** [Elringus/UnityRawInput#18]
Hi @Elringus, love RawInput, it's saved my project. Just donated $10. I know you've said the project is keyboard only, but can I make a direct $150 donation for you to add mouse button functionality? I need the raw mouse buttons, but this is well beyond my coding abilities. Please let me know if you're interested, and thank you for the great asset!

**Comment by Elringus** [comment]
Hi, Glad you found the solution useful and thanks for the tip! Unfortunately, I'm currently out of time to work on this further. I'd suggest looking for a freelancer, you'll surely find someone for the amount.

**Comment by jeffhgit** [comment]
Gotcha, thanks for the reply! Well if you're ok with this issue staying open I'll keep the offer open here for someone capable to get back to me, or close it if that's not cool and I'll keep searching!

**Comment by jeffhgit** [comment]
I'm going to create a new issue with details of the request for a code bounty and close this one

**Comment by jeffhgit** [comment]
I'm going to create a new issue with details of the request for a code bounty and close this one

**Comment by jeffhgit** [comment]
I'm going to create a new issue with details of the request for a code bounty and close this one
