### ISSUE TITLE
Add raw mouse button input functionality

### ISSUE THREAD

**Issue by eschewary** [Elringus/UnityRawInput#19]
I need the raw mouse button input to also be readable in the same manner as keyboard key presses in this project. The following resources may be useful:

https://stackoverflow.com/questions/53845288/c-sharp-hooking-to-get-raw-mouse-key-events

https://docs.microsoft.com/en-us/windows/win32/api/winuser/ns-winuser-rawmouse

**Comment by Elektroney** [comment]
added feature in #20

**Comment by Elringus** [comment]
WIP for this is in https://github.com/Elringus/UnityRawInput/tree/feat/mouse

It's almost working, but there is an issue with unresponsive mouse cursor when Unity editor window is not in focus: https://github.com/Elringus/UnityRawInput/pull/21#issuecomment-1226683385

If anyone have an idea on how to fix this, feel free to open a PR.

**Comment by silberkoenig** [comment]
I guess the mouse got slow after the Unity update. But it's just a little configuration.
In `Build Settings->Player Settings` under `Player->Resolution and Presentation` is a checkbox  `Run In Background`. When activated it works fine. Deactivated the unity process will drop the CPU and GPU usage nearly to zero in Background.

If only clicks would be the mouse events, I think then it would be fine. But maybe the mouse movement kills it to run on extremly low CPU usage.
