### ISSUE TITLE
In the example, RawKeyInput.InterceptMessages not assigned in a build

### ISSUE THREAD

**Issue by vestigialdev** [Elringus/UnityRawInput#2]
With the given example RawInputTest.cs, RawKeyInput.InterceptMessages is assigned in OnValidate(), which works in editor, but in a build OnValidate() doesn't get called. The OnValidate() docs specify "Called in the editor only". Not really a bug but can confuse a person if you're building off the example and don't know the limitation of OnValidate(). Great project otherwise!

**Comment by Elringus** [comment]
Well, this script was made for testing in editor, rather than showing how to use the package. But you're right, it could confuse a bit. Guess I'll add a comment there. Thanks for the notice!
