### ISSUE TITLE
Unity3d new Input System

### ISSUE THREAD

**Issue by IamG-Root** [elringus/UnityRawInput#37]
I'm using your package to take keyboard input even when the unity application does not have focus. Unfortunately, I noticed that this is not woking when the active input handling is set to "Both" (old input system package + new input system package). I need the new input system to take the input from my joystick. Do you know why this is not working and how to fix it? Thanks in advance.

**Comment by elringus** [comment]
You mean RawInput not working or the Unity's new input not working? If it's the last, make sure intercept messages is disabled. Otherwise something in new input is probably intercepting the messages.

**Comment by IamG-Root** [comment]
I mean that RawInput is not working, I used your sample code to test it and when Input handling is set to "input manager (old)" rawinput is working correctly. When i switch to "Both" then RawInput is not working anymore.

**Comment by IamG-Root** [comment]
I'm going to ask on the unity q&a forum, thanks.
