### ISSUE TITLE
Any leads on how to add Joystick Inputs?

### ISSUE THREAD

**Issue by lejeanf** [Elringus/UnityRawInput#7]
Priviat,
Do you have any leads on how to add Joystick Inputs?
I would like to receive input events from the xboxOne Controller while the app is not focused.
Best,

**Comment by amarillosebas** [comment]
Did you ever managed to do this?

**Comment by Elringus** [comment]
Hi, This project is only about keyboard input, but PRs to support other devices are welcome.
