### ISSUE TITLE
RawInput fires with every input not only the one specified + not working in build

### ISSUE THREAD

**Issue by ImTheDrift** [Elringus/UnityRawInput#9]
Hello! this is Drift_EX from twitter. 

I'm trying to use this solution to have Unity fire events when not in focus, but:

In the Editor the RawInput function (button down/up functions) get called even if the button pressed is a total different one. 

**And**, when I compile the project the RawInput doesn't work at all. 

Note: I am using this with Unity 2019.1.5f1

**Comment by Elringus** [comment]
I didn't test it with Unity 2019, maybe they've changed something.

**Comment by Deroido** [comment]
I think this extension is great even if it sticked to Windows only. 

But for some reason Unity 2018.2.x is crashing a lot while using RawInput.
Could you reply on that please? 
Try to Start(true) then subscribe on events. then press any key. If that's ok - restart the game mode and repeat.  For me it crashes like 1 out of 5.

I tried 2018.2.10 and 2018.2.17 (LTS)

**Comment by Elringus** [comment]
Afaik, I've used this extension with Unity 2018.3 the last time and it was working fine. Try updating to the latest 2018 LTS release.

**Comment by ImTheDrift** [comment]
@Elringus so I've gone back and installed 2018.4.17f1 which is LTS. 

I am having the same problem with the RawInput firing with everything else; It doesn't fire the first time with other buttons and waits for the right Input, but when the right input is accepted then it starts accepting ANY other input.

here's the code:
`void Start()
    {
        var workInBackground = true;
        RawKeyInput.Start(workInBackground);
        RawKeyInput.OnKeyUp += HandleKeyUp;
        RawKeyInput.OnKeyDown += HandleKeyDown;
    }

    // Update is called once per frame
    void Update()
    {
        
    }

    private void HandleKeyUp(RawKey Up)
    {
        Debug.Log("Button_Up");
    }
    private void HandleKeyDown(RawKey Up)
    {
        Debug.Log("Button_Down");
    }

    private void OnDisable()
    {
        RawKeyInput.OnKeyUp -= HandleKeyUp;
        RawKeyInput.OnKeyDown -= HandleKeyDown;
    }`

Am I doing this wrong?

**Comment by Deroido** [comment]
@Elringus Im sorry. 2018.4.17 LTS of course

@ImTheDrift I think this behavior is totally intentional
here's a little workaround I made for you to check inputs and combinations. based on RawInput 

[InputReceiver.txt](https://github.com/Elringus/UnityRawInput/files/4253743/InputReceiver.txt)
@Elringus could you please check it too? Is this my extension makes unity crash sometimes?
I repeat now Unity 2018.4.17 LTS,  previously 2018.4.10 LTS

**Comment by Elringus** [comment]
@Deroido Unfortunately, I don't have time to work on this. Try checking the crash logs, there could be some hints why it happens.

**Comment by oktomus** [comment]
Tested on Unity 2019.4 LTS, works great!
